[package]
name = "quill_statement"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
kronos = "0.1.4"
quill_utils = { path = "../quill-utils/" }
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"
