[package]
name = "quill_statement"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
kronos = "0.1.4"
quill_utils = { path = "../quill-utils/" }
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
toml = "0.5.8"

[build-dependencies]
cargo-make = "0.36.1"

[dev-dependencies]
cargo-nextest = "0.9.38"
