[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
dependencies = ["clean"]
command = "cargo"
args = ["test"]

[tasks.build]
dependencies = ["clean"]
command = "cargo"
args = ["build"]

[tasks.release]
dependencies = ["clean"]
command = "cargo"
args = [
	"build",
	"--release"
]
