[package]
name = "quill_utils"
version = { workspace = true }
edition = { workspace = true }
rust-version = "1.64"

[dependencies]
dirs-next = { workspace = true }

[build-dependencies]
cargo-make = { workspace = true }

[dev-dependencies]
cargo-nextest = { workspace = true }
